apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-socket-client
  labels:
    app: web-socket-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-socket-client
  template:
    metadata:
      labels:
        app: web-socket-client
    spec:
      containers:
        - name: web-socket-client
          image: web-socket-client:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-socket-client-service
  labels:
    app: web-socket-client
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30003
  selector:
    app: web-socket-client

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-socket-client-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    # - host: your-client-domain.com
    - http:
        paths:
          - path: /Client
            pathType: Prefix
            backend:
              service:
                name: web-socket-client-service
                port:
                  number: 80